function notice() {
    var notice = [{
        "label": "Mudanças nos impostos",
        "title": "'Não vamos transformar numa batalha', diz Lira sobre reforma tributária",
        "underTille": "",
        "subtitle": "Presidente da Câmara afirmou que proposta será voltada quando houver 'consenso'.",
        "image": "",
        "firstPage": true,
        "firstPageLeft": true,
        "firstPageRight": false,
        "secondPageLeft": false,
        "time": "",
        "smallBoxesRight": false,
        "link": "https://g1.globo.com/politica/noticia/2023/07/04/lula-transmissao-conversa-com-presidente.ghtml",
    },
    {
        "label": "Postou e foi dormir",
        "title": "A história do ator que viralizou no TikTok com mapas 'falantes'",
        "subtitle": "",
        "underTille": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\mapa1.png",  
        "firstPage": true,
        "firstPageLeft": false,
        "firstPageRight": true,
        "secondPageLeft": false,
        "time": "",
        "smallBoxesRight": false,
        "link": "https://g1.globo.com/trabalho-e-carreira/noticia/2023/07/05/postou-e-foi-dormir-o-ator-que-viralizou-da-noite-para-o-dia-no-tiktok-com-mapas-falantes.ghtml",      
    },
    {
        "label":"Cachalote na Espanha",
        "title":"Âmbar-gris: pedra rara achada dentro de baleia pode valer milhões",
        "subtitle": "🐧 Por que pinguins da Patagônia têm visitado o litoral de SP",
        "underTille": "",
        "image":"https://as2.ftcdn.net/v2/jpg/05/38/22/05/1000_F_538220558_C5fZ1vaL5lgswnewPUeZ3hEeMIlkqwHR.jpg",
        "firstPage": true,
        "firstPageLeft": false,
        "firstPageRight": true,
        "secondPageLeft": false,
        "time": "",
        "smallBoxesRight": false,
        "link":"https://g1.globo.com/mundo/noticia/2023/07/05/ambar-gris-conheca-a-pedra-rara-encontrada-dentro-de-baleia-na-espanha-que-pode-valer-r-26-milhoes.ghtml",
    },
    {
        "label": "Negociação com governantes",
        "title": "Haddad diz que reforma nãe deve mexer na Zona Franca de Manaus",
        "underTille": "Governador de SP diz que concorda 95% com a proposta",
        "subtitle": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\jacare.png",
        "firstPage": false,
        "firstPageLeft": false,
        "firstPageRight": false,
        "secondPageLeft": true,
        "time": "Há 1 hora - Em Economia",
        "smallBoxesRight": false,
        "link": "https://g1.globo.com/politica/noticia/2023/07/05/ao-lado-de-haddad-tarcisio-diz-que-concorda-95percent-com-proposta-de-reforma-tributaria.ghtml",
    },
    {
        "label": "",
        "title": "Por que o Brasil é um dos poucos países do mundo sem imposto unificado",
        "underTille": "Projeto pode criar 'cesta básica'; veja produtos sugeridos",
        "subtitle": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\reforma.png",
        "firstPage": false,
        "firstPageLeft": false,
        "firstPageRight": false,
        "secondPageLeft": true,
        "time": "Há 4 horas - Em Economia",
        "smallBoxesRight": false,
        "link": "https://g1.globo.com/economia/noticia/2023/07/05/reforma-tributaria-por-que-o-brasil-e-um-dos-poucos-paises-do-mundo-a-nao-ter-um-imposto-unificado.ghtml",
    },
    {
        "label": "Suspeita de furto",
        "title": "Fontes radioativas de Césio-137 desaparecem de mineradora em MG",
        "subtitle": "Material tem atividade 300 mil vezes menor do que o do acidente em Goiânia.",
        "underTille": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\tiktok.png",
        "firstPage": false,
        "firstPageLeft": false,
        "firstPageRight": false,
        "secondPageLeft": true,
        "time": "Há 3 horas - Em Sul de Minas",
        "smallBoxesRight": false,
        "link": "https://g1.globo.com/mg/sul-de-minas/noticia/2023/07/05/policia-investiga-furto-de-fontes-radioativas-de-cesio-137-de-mineradora-em-nazareno-em-mg.ghtml",
    },
    {
        "label": "São Paulo",
        "title": "Situação de Zé Celso se agravou, diz médica pessoal",
        "subtitle": "Diretor de teatro foi atingido pelo fogo durante incêndio em seu apartamento.",
        "underTille": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\carros.png",
        "firstPage": false,
        "firstPageLeft": false,
        "firstPageRight": false,
        "secondPageLeft": true,
        "time": "Há 36 minutos - Em São Paulo",
        "smallBoxesRight": false,
        "link": "https://g1.globo.com/carros/noticia/2023/07/05/caros-eletricos-e-luxuosos-como-sao-os-carros-da-byd-montadora-chinesa-que-tera-fabrica-na-bahia.ghtml",
    },
    {
        "label": "Viu isso aqui?", 
        "title": "",
        "subtitle": "Caso Henry: Monique Medeiros volta para a prisão por determinação do STF",
        "underTille": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\policia.png",
        "firstPage": false,
        "firstPageLeft": false,
        "firstPageRight": false,
        "secondPageLeft": false,
        "time": "",
        "smallBoxesRight": true,
        "link":"https://g1.globo.com/rj/rio-de-janeiro/noticia/2023/07/03/neymar-e-multado-r-16-milhoes-por-obra-em-lago-artificial-construido-em-mangaratiba.ghtml",
    },
    {
        "label": "",
        "title": "",
        "subtitle": "Prefeito se irrita com discurso e abandona palco com Alckmin e Tarcísio; VÍDEO",
        "underTille": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\gov.png",
        "firstPage": false,
        "firstPageLeft": false,
        "firstPageRight": false,
        "secondPageLeft": false,
        "time": "",
        "smallBoxesRight": true,
        "link": "https://g1.globo.com/ms/mato-grosso-do-sul/noticia/2023/07/02/megatraficante-do-ms-foge-da-pf-em-helicoptero-mas-segurancas-paramilitares-sao-presos-autoridades-suspeitam-de-vazamento.ghtml",
    },
    {
        "label": "",
        "title": "",
        "subtitle": "Governador de SP consola prefeito que deixou palco irritado com discurso: 'Fique tranquilo, vou te ajudar'; VÍDEO",
        "underTille": "",
        "image": "C:\\Users\\LarissaJoanaHelfer\\Desktop\\PaginaG1\\G1Clone\\img\\gov.png",
        "firstPage": false,
        "firstPageLeft": false,
        "firstPageRight": false,
        "secondPageLeft": false,
        "time": "",
        "smallBoxesRight": true,
        "link": "https://g1.globo.com/saude/noticia/2023/07/02/o-que-e-septicemia-infeccao-generalizada-que-atingiu-stenio-garcia.ghtml",
    },
]
    return notice;
}